baseurl: "/myblog"
name: "Blog of Min Zhang"
description: "Web Front-End Blog by Min Zhang"

author: "seven"
url: "https://seven777777.github.io"
loadingImg: "https://seven777777.github.io/myblog/images/loading.gif"
imgPath: "https://seven777777.github.io/myblog/images"

paginate: 6
paginate_path: "/page:num"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink: pretty

plugins:
- jekyll-paginate
- jemoji
port: 4001

# gitalk:
#     owner: seven777777
#     repo: blog-comment
#     clientID: 6140c3098c5e95fcf6a9
#     clientSecret: 4c660ac4037d51cfd8edbccadac4c8cb8a611425
