baseurl: "/myblog"
name: "Blog of Min Zhang"
description: "Web Front-End Blog by Min Zhang"

url: "https://seven777777.github.io"
loadingImg: "https://seven777777.github.io/myblog/images/loading.gif"
imgPath: "https://seven777777.github.io/myblog/images"


paginate: 4
paginate_path: "/page:num"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink: pretty

plugins:
- jekyll-paginate
port: 4001
